function InitPrefectureList() {
  return [
    { PrefectureCode: '01', Prefecture: '北海道', selected: false },
    { PrefectureCode: '02', Prefecture: '青森', selected: false },
    { PrefectureCode: '03', Prefecture: '岩手', selected: false },
    { PrefectureCode: '04', Prefecture: '宮城', selected: false },
    { PrefectureCode: '05', Prefecture: '秋田', selected: false },
    { PrefectureCode: '06', Prefecture: '山形', selected: false },
    { PrefectureCode: '07', Prefecture: '福島', selected: false },
    { PrefectureCode: '08', Prefecture: '茨城', selected: false },
    { PrefectureCode: '09', Prefecture: '栃木', selected: false },
    { PrefectureCode: '10', Prefecture: '群馬', selected: false },
    { PrefectureCode: '11', Prefecture: '埼玉', selected: false },
    { PrefectureCode: '12', Prefecture: '千葉', selected: false },
    { PrefectureCode: '13', Prefecture: '東京', selected: false },
    { PrefectureCode: '14', Prefecture: '神奈川', selected: false },
    { PrefectureCode: '15', Prefecture: '新潟', selected: false },
    { PrefectureCode: '16', Prefecture: '富山', selected: false },
    { PrefectureCode: '17', Prefecture: '石川', selected: false },
    { PrefectureCode: '18', Prefecture: '福井', selected: false },
    { PrefectureCode: '19', Prefecture: '山梨', selected: false },
    { PrefectureCode: '20', Prefecture: '長野', selected: false },
    { PrefectureCode: '21', Prefecture: '岐阜', selected: false },
    { PrefectureCode: '22', Prefecture: '静岡', selected: false },
    { PrefectureCode: '23', Prefecture: '愛知', selected: false },
    { PrefectureCode: '24', Prefecture: '三重', selected: false },
    { PrefectureCode: '25', Prefecture: '滋賀', selected: false },
    { PrefectureCode: '26', Prefecture: '京都', selected: false },
    { PrefectureCode: '27', Prefecture: '大阪', selected: false },
    { PrefectureCode: '28', Prefecture: '兵庫', selected: false },
    { PrefectureCode: '29', Prefecture: '奈良', selected: false },
    { PrefectureCode: '30', Prefecture: '和歌山', selected: false },
    { PrefectureCode: '31', Prefecture: '鳥取', selected: false },
    { PrefectureCode: '32', Prefecture: '島根', selected: false },
    { PrefectureCode: '33', Prefecture: '岡山', selected: false },
    { PrefectureCode: '34', Prefecture: '広島', selected: false },
    { PrefectureCode: '35', Prefecture: '山口', selected: false },
    { PrefectureCode: '36', Prefecture: '徳島', selected: false },
    { PrefectureCode: '37', Prefecture: '香川', selected: false },
    { PrefectureCode: '38', Prefecture: '愛媛', selected: false },
    { PrefectureCode: '39', Prefecture: '高知', selected: false },
    { PrefectureCode: '40', Prefecture: '福岡', selected: false },
    { PrefectureCode: '41', Prefecture: '佐賀', selected: false },
    { PrefectureCode: '42', Prefecture: '長崎', selected: false },
    { PrefectureCode: '43', Prefecture: '熊本', selected: false },
    { PrefectureCode: '44', Prefecture: '大分', selected: false },
    { PrefectureCode: '45', Prefecture: '宮崎', selected: false },
    { PrefectureCode: '46', Prefecture: '鹿児島', selected: false },
    { PrefectureCode: '47', Prefecture: '沖縄', selected: false },
  ];
}

export default InitPrefectureList;
